### ISSUE TITLE
Dezoomify extension opens separate windows for http and https versions of a URI

### ISSUE THREAD

**Issue by yango** [lovasoa/dezoomify-extension#10]
Test is here:
https://digitalcollections.tcd.ie/concern/parent/hm50tr726/folios/qv33rw81j#?c=0&m=0&s=0&cv=0&xywh=-3367%2C0%2C9164%2C3150
The extension opens two links. Is there any option to ignore http version of a link?

**Comment by lovasoa** [comment]
Fixed in 0.4.3
