### ISSUE TITLE
new site support: artsy.net

### ISSUE THREAD

**Issue by surao101** [lovasoa/dezoomify-extension#14]
Trying to download images from artsy.net.

Example url - https://www.artsy.net/artwork/camille-pissarro-la-briqueterie-delafolie-a-eragny

1. First tried https://ophir.alwaysdata.net/dezoomify/dezoomify.html
Choosing "Select automatically"
Result - Oops, we have a problem

2. Tried inspect element and then network and tried the url for every js (no DZI file found) and jpg using https://ophir.alwaysdata.net/dezoomify/dezoomify.html
Result - Oops, we have a problem

Tried dezoomify-rs with url - https://www.artsy.net/artwork/camille-pissarro-la-briqueterie-delafolie-a-eragny
Result :
```
Enter an URL or a path to a tiles.yaml file: 
https://www.artsy.net/artwork/camille-pissarro-la-briqueterie-delafolie-a-eragny
Trying to locate a zoomable image...
Downloading https://www.artsy.net/artwork/camille-pissarro-la-briqueterie-delafolie-a-eragny...
Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: 4:53 Qualified name is invalid: 

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by lovasoa** [comment]
Hello, 
  The zoomable image format used by artsy is not supported by dezoomify (and thus by the dezoomify extension). However, you can still download images using the generic dezoomer.
  See https://github.com/lovasoa/dezoomify/issues/129
