### ISSUE TITLE
add support for rijksmuseum micrio

### ISSUE THREAD

**Issue by CodemasterTH** [lovasoa/dezoomify-extension#23]
Hello everyone,

 I am having issues when trying to download http://hdl.handle.net/10934/RM0001.COLLECT.66586

Dezoomify reports:

```
Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
http://hdl.handle.net/10934/RM0001.COLLECT.66586

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)
```
I don't understand this message. Can someone please help me ?

**Comment by CodemasterTH** [comment]
Hello lovasoa, i have an alternative solution you can implement for dezoomify when downloading from rijksmuseum micrio. I did some tests and found a pattern. On all of them the meta-information files were located under https://q42imageserver.appspot.com/api/getTilesInfo?object_id=
With the object_id parameter being the id code shown in the home URL containing the zoomable pic. That object number is also stored in a div under the group-data div. For example this one here 
https://www.rijksmuseum.nl/nl/collectie/NG-2011-18-12-83
The NG-2011-18-12-83 is the object id parameter you need for the meta-information file
So it will be https://q42imageserver.appspot.com/api/getTilesInfo?object_id=NG-2011-18-13-16
I have tried putting the URL above in the dezoomify website and it worked fine.
I'm not aware if other images have their meta-information files under another URL. 
Either way the getTilesInfo? script under JS requests should work fine as well.

**Comment by lovasoa** [comment]
@CodemasterTH : Yes, it should just be a matter of adding two regexps to background.js, no need to look at the dom : https://github.com/lovasoa/dezoomify-extension/blob/master/background.js

Are you interested in making a pull request ?

**Comment by CodemasterTH** [comment]
@lovasoa yes i'm interested, just did a fork and will be submitting the pull request soon

**Comment by CodemasterTH** [comment]
@lovasoa i'm submitting the pull request right now.
