### ISSUE TITLE
Website support request

### ISSUE THREAD

**Issue by rafograph** [lovasoa/dezoomify-extension#25]
Hi lovasoa,

thank you very much for keeping up this amazing software.
I would ask you if it is possible to add the support for downloading from this website:
https://magazines.iaddb.org/issue/GG/1923-01-01/edition/0-0/page/1

I would be glad to make a donation if this be made possible.
Also if not possible but just in case. :D

Thank you in advance.

**Comment by lovasoa** [comment]
This website uses the memorix viewer which is supported by dezoomify (but not yet by the browser extension).

See https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://images.memorix.nl/sra/topviewjson/beeldbank/98b8c953-4a89-5b87-3345-519f5e25ade3?checkIfTiled=1

**Comment by rafograph** [comment]
Thank you very much. How can I contribute with a donation?

**Comment by lovasoa** [comment]
You're welcome :)

You can make a recurring donation through github sponsors here: https://github.com/sponsors/lovasoa
If enough recurring donations are collected, I should be able to pay for a global image proxy allowing image downloads and unlimited google arts downloads (see https://github.com/lovasoa/dezoomify/issues/337).

If you just want to make a one time donation, you can use my paypal : https://paypal.me/olojkine

:smiling_face_with_three_hearts:
