### ISSUE TITLE
Image not detected/detected but no URL appears

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify-extension#30]
Good morning @lovasoa. 
I hope You're fine.
Today I realized that the extension (Mozilla Firefox version) either fails to detect the image where it previously detected it (https://luna.lib.uchicago.edu/luna/servlet/detail/UCHICAGO~2~2~554~1240064:Deutsche-&--Romanen-in-Su%CC%88d-Tiro?qvq=q:_luna_media_exif_filename%3DG6713-B6E1-1877-P4.tif&mi=0&trs=1) or it detects it (https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~317264~90086560:Covers--Atlas-of-Egypt-Volume-I?sort=pub_list_no_initialsort%2Cpub_date%2Cpub_list_no%2Cseries_no&qvq=q:%3D%22Egypt.%20Wizarat%20al-Maliyah%22;sort:pub_list_no_initialsort%2Cpub_date%2Cpub_list_no%2Cseries_no;lc:RUMSEY~8~1&mi=15&trs=199) but **no** URL appears on the website **dezoomify.ophir.dev**😭! I don't know if I'm doing something wrong or if something happened: until last month the extension worked perfectly.
_Warning_: the two urls are mere samples of images that I've **already** dezoomified using extension + rs combo, so I don't need the URLs to dezoomify them.

**Comment by lovasoa** [comment]
Thank you for reporting this! This is linked to the site update I had to make earlier this week. 

The extension links to https://dezoomify.ophir.dev/dezoomify/dezoomify.html instead of the new more simple https://dezoomify.ophir.dev/

**Comment by lovasoa** [comment]
Exactly, just wait, I'll close this issue when this is fixed.

**Comment by Arekkusu1998** [comment]
Thank You very very much, @lovasoa!!!
