### ISSUE TITLE
new site support: https://dnnt.mzk.cz

### ISSUE THREAD

**Issue by lludvik** [lovasoa/dezoomify-extension#32]
Example URLs
dezoomify detect url https://dnnt.mzk.cz/search/iiif/uuid:270d5cba-eed2-485c-bd73-cd8189879562/info.json
need replace with https://dnnt.mzk.cz/search/img?pid=uuid:270d5cba-eed2-485c-bd73-cd8189879562&stream=IMG_FULL

**Comment by lludvik** [comment]
**edit background.js**

function openDezoomify(image_url) {
if (image_url.indexOf("dnnt.mzk.cz") > -1) {
    image_url = image_url.replace(/\/info.json/, '&stream=IMG_FULL');
    const url = image_url;
    return chrome.tabs.create({ url });
} else {
    const url = DEZOOMIFY_URL + image_url;
    return chrome.tabs.create({ url });            
}
}

**Comment by lovasoa** [comment]
see https://github.com/lovasoa/dezoomify/issues/589#issuecomment-980810836
