### ISSUE TITLE
臺北故宮數據庫圖片無法拼圖請您解決

### ISSUE THREAD

**Issue by gongyugudao** [lovasoa/dezoomify-extension#34]
@感謝
Dezoomify 
https://dezoomify.ophir.dev/#https://iiifod.npm.gov.tw/iiif/2/K1C%2FK1C004888N000000000PAB/2048,5120,1024,1024/512,/0/default.jpg

無法獲取？

**Comment by lovasoa** [comment]
no comprendo :smiling_face_with_tear:

**Comment by gongyugudao** [comment]
Hello, can't make the puzzle, please help? &nbsp;grateful



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ophir LOJKINE ***@***.***&gt;
发送时间: 2022年1月12日 18:27
收件人: lovasoa/dezoomify-extension ***@***.***&gt;
抄送: gongyugudao ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lovasoa/dezoomify-extension] 臺北故宮數據庫圖片無法拼圖請您解決 (Issue #34)





 
no comprendo 🥲
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
