### ISSUE TITLE
台北故宫数据库图片无法拼图请您解决 

### ISSUE THREAD

**Issue by gongyugudao** [lovasoa/dezoomify-extension#35]
台北故宫数据库图片无法拼图请您解决 
 
@感谢
Dezoomify
https://dezoomify.ophir.dev/#https://iiifod.npm.gov.tw/iiif/2/K1C%2FK1C004888N000000000PAB/2048,5120,1024,1024/512,/0/default.jpg

无法获取？

**Comment by lovasoa** [comment]
je ne comprends pas :)

**Comment by gongyugudao** [comment]
The Taipei Palace Museum database picture cannot be assembled, please solve it

@grateful
to zoom
https://dezoomify.ophir.dev/#https://iiifod.npm.gov.tw/iiif/2/K1C%2FK1C004888N000000000PAB/2048,5120,1024,1024/512,/0/default.jpg

Can't get it?

**Comment by gongyugudao** [comment]
Can't get image, please help.

**Comment by lovasoa** [comment]
![image](https://user-images.githubusercontent.com/552629/149140214-1b1f1461-e2d4-49a3-8f6d-3039580424e8.png)
