### ISSUE TITLE
https://artsandculture.google.com/asset/mystery-and-melancholy-of-a-street-girl-running-with-a-hoop/HQGg0C62z_eSsw?ms=%7B%22x%22%3A0.5109590314612573%2C%22y%22%3A0.4294279811845748%2C%22z%22%3A11%2C%22size%22%3A%7B%22width%22%3A0.9227467811158798%2C%22height%22%3A0.4183168316831683%7D%7D

### ISSUE THREAD

**Issue by onesun0077** [lovasoa/dezoomify-extension#39]

**Comment by lovasoa** [comment]
Google changed something to the arts and culture website and the downloader needs to be changed. To avoid duplicate issues, let's centralize the discussion on https://github.com/lovasoa/dezoomify-rs/issues/178

**Comment by lovasoa** [comment]
dezoomify now works again with google arts and culture :slightly_smiling_face:
