### ISSUE TITLE
The british library is not working

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify-extension#4]
Reported by @SB2020-eye 

See : https://github.com/lovasoa/dezoomify-extension/issues/1#issuecomment-599161229

the extension gives the wrong link for http://www.bl.uk/manuscripts/Viewer.aspx?ref=cotton_ms_nero_d_iv_fs001r

**Comment by SB2020-eye** [comment]
Thanks for looking at it.

I retested using different pages, browsers, and methods. Here are my results:

1. Chrome, Cut and paste source address, into Dezoomify webpage (https://ophir.alwaysdata.net/dezoomify/dezoomify.html) --
Source: http://www.bl.uk/manuscripts/Viewer.aspx?ref=cotton_ms_nero_d_iv_f100r
Result: WORKS AS DESCRIBED on Dezoomify webpage

2. Chrome, Dezoomify extension on source webpage
Source: http://www.bl.uk/manuscripts/Viewer.aspx?ref=cotton_ms_nero_d_iv_f100r
Result: "! OOPS, WE HAVE A PROBLEM"
Note: The source address gets changed by the extension, adding ".dzi" at the end (http://www.bl.uk/manuscripts/Proxy.ashx?view=cotton_ms_nero_d_iv_f100r.dzi). Also, as I mentioned previously, the icon is always blue in Chrome (not gray, then blue upon activation, as the instructions describe).

Firefox - IDENTICAL RESULTS AS 1 AND 2, except for these minor differences:
- the Dezoomify extension icon starts as gray, then turns blue upon activation (like your instructions describe)
- for what it's worth, the badge that appears is blue in Chrome, and red in Firefox; but that may be on purpose. I'm just noting the differences observed.

Here are pics in Firefox. (I did use a different page as source: http://www.bl.uk/manuscripts/Viewer.aspx?ref=cotton_ms_nero_d_iv_f101r)

![image](https://user-images.githubusercontent.com/56878280/77233288-e0cefe00-6b7c-11ea-9941-28b24197149c.png)

![image](https://user-images.githubusercontent.com/56878280/77233194-4969ab00-6b7c-11ea-8840-adc8c1261751.png)

**Comment by SB2020-eye** [comment]
Title of issue should read "british". :)

**Comment by lovasoa** [comment]
The chrome web store takes very long to review each version of the extension, so the differences between chrome and firefox are due to the fact that the chrome extension is outdated. However, they just finished the review of the previous version, so I'll be able to upload a new version. I want to fix as many bugs as possible in it, since we probably won't be able to update it again for a few weeks when we submit it.

**Comment by SB2020-eye** [comment]
Hi again. How can I tell whether or not I'm getting the largest resolution files possible from this site? The images I was able to obtain tend to be about 3800 KB (with a few as low as the mid-2000s and a few in the 5000s).

My hope was to find something much better.

**Comment by lovasoa** [comment]
Hello,
  dezoomify always downloads the largest available zoom level, but may reduce the final size of the image [if it's very large](https://github.com/lovasoa/dezoomify/wiki/Very-large-images). But at 3.8 Mb, I think you're far from the limit. The easiest way to tell if you have the best version available is just to visually compare the image in the zoomable image viewer on the original site and the image you downloaded from dezoomify.

**Comment by SB2020-eye** [comment]
Thanks.

**Comment by lovasoa** [comment]
Just tested, seems to be fixed in the latest version.
