### ISSUE TITLE
No magnifying glass icon

### ISSUE THREAD

**Issue by pigsonthewing** [lovasoa/dezoomify-extension#45]
I can not download any image using this extension; I get no magnifying glass icon on the address bar.

Tested, for example, on:

https://www.nga.gov/collection/art-object-page.56739.html

**Comment by pigsonthewing** [comment]
Just noting that this persists in Firefox 117.0.1

It also persists after removing the extension, restarting Firefox, and re-adding the extension.

**Comment by pigsonthewing** [comment]
Why was this closed? Although a work-around has been described (again: thank you) the underlying issue of the absent address-bar icon persists.

**Comment by lovasoa** [comment]
Firefox used to display extensions directly next to the address bar and now there is this extensions button. You can still move it if you want.
