### ISSUE TITLE
Unable to download an image from google arts and culture

### ISSUE THREAD

**Issue by Goarkh** [lovasoa/dezoomify-extension#47]
Oops, we have a problem
An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave.

You can try to install the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/), that can find the address of dezoomable images automatically on the pages you visit.

If that does not help, then you should read our [Frequently Asked Questions](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ).

If your image is extremely large and it does not show in your browser, see our [advices for large images](https://github.com/lovasoa/dezoomify/wiki/Very-large-images).

Dezoomify also has a github bug tracker, where you can interact with other users as well as with me, the developer, if you create a free github account :

[search for issues similar to yours](https://github.com/lovasoa/dezoomify/issues?q=artsandculture.google.com): maybe someone already managed to download images from your website and explained how.
[report a bug](https://github.com/lovasoa/dezoomify/issues/new?template=1_bug_report.md) if you think this is an issue with dezoomify itself. Use this link only if the image is in a format that is supported by dezoomify, yet it doesn't open correctly. I try to fix bugs in dezoomify in a timely manner.
[ask for support with this particular site](https://github.com/lovasoa/dezoomify/issues/new?labels=new%20site%20support&title=artsandculture.google.com&body=Hello%20everyone%2C%0A%0A%20I%20am%20having%20issues%20when%20trying%20to%20download%20https%3A%2F%2Fartsandculture.google.com%2Fasset%2Fwoman-holding-a-balance-johannes-vermeer%2F-wHFDKu7-mhjtQ%0A%0ADezoomify%20reports%3A%0A%0A%60%60%60%0AUncaught%20Error%3A%20Our%20server%20has%20received%20too%20many%20requests%2C%20and%20our%20provider%20is%20blocking%20new%20requests.%20You%20can%20donate%20on%20https%3A%2F%2Fgithub.com%2Fsponsors%2Flovasoa%20to%20participate%20to%20the%20hosting%20fees.%20Once%20we%20collect%20over%205%24%2Fmonth%20overall%2C%20we%20will%20switch%20to%20a%20paid%20plan%20of%20the%20provider%2C%20allowing%20more%20requests%20to%20go%20through%20every%20day.%20For%20more%20details%2C%20see%20https%3A%2F%2Fgithub.com%2Flovasoa%2Fdezoomify%2Fissues%2F337%23issuecomment-773498488.%0A%0A(https%3A%2F%2Fdezoomify.ophir.dev%2Fzoommanager.js%3A217)%0A%60%60%60%0AI%20don%27t%20understand%20this%20message.%20Can%20someone%20please%20help%20me%20%3F): I do not have a lot of time to allocate to dezoomify, but sometimes, I add support for new websites. You can also [contact me](https://ophir.dev/) if you want paid personalized support.
If you decide to write something on the bug tracker, then please be polite, try to explain your issue in details in english, and include the technical details below.
Uncaught Error: Our server has received too many requests, and our provider is blocking new requests. You can donate on https://github.com/sponsors/lovasoa to participate to the hosting fees. Once we collect over 5$/month overall, we will switch to a paid plan of the provider, allowing more requests to go through every day. For more details, see https://github.com/lovasoa/dezoomify/issues/337#issuecomment-773498488.

(https://dezoomify.ophir.dev/zoommanager.js:217)

**Comment by mastix01** [comment]
The add on will not work anymore it seems on Google Arts. If somebody knows of an alternative that works correctly on Google Arts it would be great to mention it here. 

This was an amazing addon in the past. I guess some update on Google side has made this add on worthless for the time being.

**Comment by lovasoa** [comment]
Hello ! 
  Both the extension and dezoomify still work, but we have hit our request limit. The error message you see should be saying exactly what is happening:

>  Our server has received too many requests, and our provider is blocking new requests. **You can donate** on https://github.com/sponsors/lovasoa to participate to the hosting fees. Once we collect over 5$/month overall, we will switch to a paid plan of the provider, allowing more requests to go through every day. For more details, see https://github.com/lovasoa/dezoomify/issues/337#issuecomment-773498488.
