### ISSUE TITLE
Please add support to https://www2.ntj.jac.go.jp

### ISSUE THREAD

**Issue by afgks** [lovasoa/dezoomify-extension#61]
Hello, could you please add support to this website? Here is [an example](https://www2.ntj.jac.go.jp/dglib/collections/viewer?division=collections&class=nishikie&type=painter&ikana=%E3%81%86%E3%81%9F%E3%81%8C%E3%82%8F+%E3%81%86%E3%81%9F%E3%81%97%E3%81%92&ititle=%E6%AD%8C%E5%B7%9D+%E6%AD%8C%E9%87%8D&istart=0&iselect=%E3%81%86&rid=5000094&pid=3&name=last&trace=refine&trace=result&trace=detail&trace=zoom&rpid=all&did=1256)

A list of artwork on the website:

https://www2.ntj.jac.go.jp/dglib/collections/search_result?division=collections&class=nishikie&type=painter&ikana=%E3%81%86%E3%81%9F%E3%81%8C%E3%82%8F+%E3%81%86%E3%81%9F%E3%81%97%E3%81%92&ititle=%E6%AD%8C%E5%B7%9D+%E6%AD%8C%E9%87%8D&istart=0&iselect=%E3%81%86&rid=5000094&pid=3&name=last&trace=refine&trace=result&rpid=all

**Comment by afgks** [comment]
Another website: https://dl.ndl.go.jp/

Examples:
https://dl.ndl.go.jp/pid/1307308/2/1
https://dl.ndl.go.jp/pid/1305910/2/1

**Comment by DigitalCurator** [comment]
Their developer interestingly customized the Zoomify technology using Base64 conversion, pretty ingenius, probably to prevent visitors from downloading the copyrighted images. It can still be downloaded of course, but it takes quite some time and effort.

**Comment by DigitalCurator** [comment]
Nice artwork ;-)

I like how the Japanese developer utilise Base64 to protect their copyrighted image, nicely done.

**Comment by DigitalCurator** [comment]
Scroll down the webpage:
![image](https://github.com/user-attachments/assets/e83c020d-d3fe-4004-9ce8-d655aaafb964)
<sub>Translated text on page.</sub>

**Comment by afgks** [comment]
Hello, there is no such button on the https://www2.ntj.jac.go.jp website. Can you please check https://www2.ntj.jac.go.jp/dglib/collections/viewer?division=collections&class=nishikie&type=painter&ikana=%E3%81%86%E3%81%9F%E3%81%8C%E3%82%8F+%E3%81%86%E3%81%9F%E3%81%97%E3%81%92&ititle=%E6%AD%8C%E5%B7%9D+%E6%AD%8C%E9%87%8D&istart=0&iselect=%E3%81%86&rid=5000094&pid=3&name=last&trace=refine&trace=result&trace=detail&trace=zoom&rpid=all&did=1256

**Comment by DigitalCurator** [comment]
Please take note of the copyright notice on the website.

```
All copyrights to this website belong to the Japan Arts Council, an independent administrative institution.
Any reproduction or modification without permission is strictly prohibited. In addition, any reproduction or copying without permission is also prohibited.

Copyright(C) 2023 Japan Arts Council, All rights reserved.
```
You can either write a request to a Japan Arts Council for a copy of their digital print. Or, you can always message me your request on my [profile](https://github.com/DigitalCurator), indicating your area of academic research or purpose of the file download so that I may assist you in retrieving your requested materials. 

Thanks.
