### ISSUE TITLE
greatchicagofire.org

### ISSUE THREAD

**Issue by SmithJustinL** [lovasoa/dezoomify-extension#9]
Normally the plugin will work on a given website. I was trying to get an image here:

https://www.greatchicagofire.org/view-item/165/

And no matter what I did, I could not get the plugin to work. I cannot get images at all from this site in fact. Any help appreciated.

**Comment by lovasoa** [comment]
Hello, 
  This zoomable image format is not supported, but it's easy to download with dezoomify. See : https://github.com/lovasoa/dezoomify/issues/382

**Comment by lovasoa** [comment]
The template url to use in dezoomify for your example : 

[`https://www.greatchicagofire.org/sites/greatchicagofire.org/files/tiles/_images/i02870/layer0010/tile{{Y:04}}n{{X:04}}.jpg`](https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.greatchicagofire.org/sites/greatchicagofire.org/files/tiles/_images/i02870/layer0010/tile{{Y:04}}n{{X:04}}.jpg)

**Comment by lovasoa** [comment]
![chicago fire](https://user-images.githubusercontent.com/552629/91959434-e2dee080-ed08-11ea-948b-cd2704e273c6.jpg)

**Comment by SmithJustinL** [comment]
Thank you very much!


Servus tuus,

Justin L. Smith
Huntington, WV

**Comment by SmithJustinL** [comment]
Hello,

I'm trying to download this full image:

https://sg30p0.familysearch.org/service/records/storage/deepzoomcloud/dz/v1/3:1:S3HT-6PNS-ZH4/image_files/12/9_5.jpg

The xml file is:
https://sg30p0.familysearch.org/service/records/storage/deepzoomcloud/dz/v1/3:1:S3HT-6PNS-ZH4/image.xml

I just cannot figure out how to download this! Any help appreciated!


Servus tuus,

Justin L. Smith
Huntington, WV

**Comment by Nickgtzaf420** [comment]
Any one from Huntington WV trying to fuck
